CREATE TABLE "HR"."PUESTOTRABAJO" 
   (	"PUESTOTRABAJOID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PUESTO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"EDITADOPOR" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"HABILITADO" NUMBER(1,0) NOT NULL ENABLE, 
	"FECHACREACION" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("PUESTOTRABAJOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
